# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dave Quah
email: quahdave@gmail.com
description: > # this means to ignore newlines until "url:"
  I'm a Dave-loper (pun intended) in Government Technology Agency of Singapore,
  and am part of the Digital Design and Development Team (DCUBE).
  We build amazing products to help our citizens.
url: "/" # the base hostname & protocol for your site
facebook: https://www.facebook.com/milleus
googleplus: https://plus.google.com/u/1/111152598083769319838
linkedin: https://www.linkedin.com/in/milleus
github: https://github.com/Milleus

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
